### ISSUE TITLE
wassabi server access denied

### ISSUE THREAD

**Issue by j0seo** [StacyYang/gluoncv-torch#29]
The pretrained model can't be loaded because access to the server is denied.

**Comment by tjyuyao** [comment]
Same issue. Any solution?

**Comment by weixj1998** [comment]
@j0seo @tjyuyao Hello, I met the same issue. Do you have any solution now? Thanks.

**Comment by weixj1998** [comment]
@cclauss How can I obtain the corresponding pre-training model at present? the access to the server is denied. thanks!

**Comment by DarthRL** [comment]
@zhanghang1989 Would you kindly fix the server problem again? Thanks!

**Comment by zhanghang1989** [comment]
Could you try access again?

**Comment by DarthRL** [comment]
> Could you try access again?

Works perfectly. Many thanks!

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by weixj1998** [comment]
> > Could you try access again?
> 
> Works perfectly. Many thanks!

How to solve it? Run the code as before? Thanks!

**Comment by DarthRL** [comment]
> > > Could you try access again?
> > 
> > 
> > Works perfectly. Many thanks!
> 
> How to solve it? Run the code as before? Thanks!

Yeah just run it normally

**Comment by weixj1998** [comment]
> > > > Could you try access again?
> > > 
> > > 
> > > Works perfectly. Many thanks!
> > 
> > 
> > How to solve it? Run the code as before? Thanks!
> 
> Yeah just run it normally

Thanks a lot! I was able to run this code.

**Comment by cclauss** [comment]
Can this issue be closed?
